// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SAM.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RibbonEnableDisable")]
    public partial class RibbonEnableDisableFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RibbonEnableDisable.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RibbonEnableDisable", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Home Ribbon Enabled and Disabled")]
        [NUnit.Framework.CategoryAttribute("Ribbon")]
        [NUnit.Framework.TestCaseAttribute("Paste", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Copy", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Undo", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Redo", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Cut", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Delete", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Rename", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Auto Recalculate", "Enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Insert", "Enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Find", "Enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Show Ancestry", "Enabled", null)]
        public virtual void HomeRibbonEnabledAndDisabled(string ribbon, string visibility, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Ribbon"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Home Ribbon Enabled and Disabled", null, @__tags);
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
testRunner.Given("a user opens SAM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
testRunner.When("the warning message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
testRunner.Then("the user can click on the OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
testRunner.And(string.Format("the ribbon \"{0}\" has a \"{1}\"", ribbon, visibility), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Layout Ribbon Enabled and Disabled")]
        [NUnit.Framework.TestCaseAttribute("Design Explorer", "Enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Graphics", "Enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Message panel", "Enabled", null)]
        [NUnit.Framework.TestCaseAttribute("kcl panel", "Enabled", null)]
        public virtual void LayoutRibbonEnabledAndDisabled(string ribbon, string visibilty, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Layout Ribbon Enabled and Disabled", null, exampleTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 27
testRunner.Given("a user opens SAM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
testRunner.When("the warning message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
testRunner.Then("the user can click on the OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
testRunner.And(string.Format("the ribbon \"{0}\" has a \"<visibility>\"", ribbon), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Temp Location Enabled and Disabled")]
        [NUnit.Framework.CategoryAttribute("Ribbon")]
        [NUnit.Framework.TestCaseAttribute("Link to Paramarine", "Disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Link to Excel", "Disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Trace Anscestor", "Enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Trace Descendents", "Enabled", null)]
        public virtual void TempLocationEnabledAndDisabled(string ribbon, string visibilty, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Ribbon"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Temp Location Enabled and Disabled", null, @__tags);
#line 41
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 42
testRunner.Given("a user opens SAM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
testRunner.When("the warning message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
testRunner.Then("the user can click on the OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
testRunner.And(string.Format("the ribbon \"{0}\" has a \"<visibility>\"", ribbon), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SAM Ribbon enabled and disabled")]
        [NUnit.Framework.CategoryAttribute("Ribbon")]
        [NUnit.Framework.TestCaseAttribute("All Scenarios", "Disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Additional Scenarios", "Disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Random Scenario", "Disabled", null)]
        [NUnit.Framework.TestCaseAttribute("Update Results", "Disabled", null)]
        public virtual void SAMRibbonEnabledAndDisabled(string ribbon, string visibilty, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Ribbon"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SAM Ribbon enabled and disabled", null, @__tags);
#line 56
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 57
testRunner.Given("a user opens SAM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
testRunner.When("the warning message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
testRunner.Then("the user can click on the OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
testRunner.And(string.Format("the ribbon \"{0}\" has a \"<visibility>\"", ribbon), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

